[package]
name = "sim-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
ffmpeg-next = "6.1.1"
itertools = "0.12.1"
rayon = "1.9.0"

